In [2]:
#import libraries
import pandas as pd
import numpy as np


In [3]:
#load dc_properties.csv into dataframe
location = 'datasets/dc_properties.csv'
df = pd.read_csv(location)

C:\Users\Laura\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (18,19,20,21,22,23,24,33,34,35,37,43,45) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [4]:
# original row column counts      (158957, 49)
df.shape

(158957, 49)

In [5]:
#look at first 5 rows of data
df.head()


Unnamed: 0  BATHRM  HF_BATHRM           HEAT AC  NUM_UNITS  ROOMS  BEDRM  \
0           0       4          0      Warm Cool  Y        2.0      8      4   
1           1       3          1      Warm Cool  Y        2.0     11      5   
2           2       3          1  Hot Water Rad  Y        2.0      9      5   
3           3       3          1  Hot Water Rad  Y        2.0      8      5   
4           4       2          1      Warm Cool  Y        1.0     11      3   

      AYB  YR_RMDL  ...  LONGITUDE  ASSESSMENT_NBHD ASSESSMENT_SUBNBHD  \
0  1910.0   1988.0  ... -77.040832       Old City 2   040 D Old City 2   
1  1898.0   2007.0  ... -77.040764       Old City 2   040 D Old City 2   
2  1910.0   2009.0  ... -77.040678       Old City 2   040 D Old City 2   
3  1900.0   2003.0  ... -77.040629       Old City 2   040 D Old City 2   
4  1913.0   2012.0  ... -77.039361       Old City 2   040 D Old City 2   

   CENSUS_TRACT CENSUS_BLOCK    WARD  SQUARE          X          Y QUADRANT  
0        4201.0  004201 2006  Ward 2     152 -77.040429  38.914881       NW  
1        4201.0  004201 2006  Ward 2     152 -77.040429  38.914881       NW  
2        4201.0  004201 2006  Ward 2     152 -77.040429  38.914881       NW  
3        4201.0  004201 2006  Ward 2     152 -77.040429  38.914881       NW  
4        4201.0  004201 2006  Ward 2     152 -77.040429  38.914881       NW  

[5 rows x 49 columns]

In [6]:
#What are the columns?
df.columns

Index(['Unnamed: 0', 'BATHRM', 'HF_BATHRM', 'HEAT', 'AC', 'NUM_UNITS', 'ROOMS',
       'BEDRM', 'AYB', 'YR_RMDL', 'EYB', 'STORIES', 'SALEDATE', 'PRICE',
       'QUALIFIED', 'SALE_NUM', 'GBA', 'BLDG_NUM', 'STYLE', 'STRUCT', 'GRADE',
       'CNDTN', 'EXTWALL', 'ROOF', 'INTWALL', 'KITCHENS', 'FIREPLACES',
       'USECODE', 'LANDAREA', 'GIS_LAST_MOD_DTTM', 'SOURCE', 'CMPLX_NUM',
       'LIVING_GBA', 'FULLADDRESS', 'CITY', 'STATE', 'ZIPCODE', 'NATIONALGRID',
       'LATITUDE', 'LONGITUDE', 'ASSESSMENT_NBHD', 'ASSESSMENT_SUBNBHD',
       'CENSUS_TRACT', 'CENSUS_BLOCK', 'WARD', 'SQUARE', 'X', 'Y', 'QUADRANT'],
      dtype='object')

In [7]:
#where are the null values?
df.isnull().sum()


Unnamed: 0                 0
BATHRM                     0
HF_BATHRM                  0
HEAT                       0
AC                         0
NUM_UNITS              52261
ROOMS                      0
BEDRM                      0
AYB                      271
YR_RMDL                78029
EYB                        0
STORIES                52305
SALEDATE               26770
PRICE                  60741
QUALIFIED                  0
SALE_NUM                   0
GBA                    52261
BLDG_NUM                   0
STYLE                  52261
STRUCT                 52261
GRADE                  52261
CNDTN                  52261
EXTWALL                52261
ROOF                   52261
INTWALL                52261
KITCHENS               52262
FIREPLACES                 0
USECODE                    0
LANDAREA                   0
GIS_LAST_MOD_DTTM          0
SOURCE                     0
CMPLX_NUM             106696
LIVING_GBA            106696
FULLADDRESS            52917
CITY          

In [8]:
#samething, different function. where are the na's?"
df.isna().sum()

Unnamed: 0                 0
BATHRM                     0
HF_BATHRM                  0
HEAT                       0
AC                         0
NUM_UNITS              52261
ROOMS                      0
BEDRM                      0
AYB                      271
YR_RMDL                78029
EYB                        0
STORIES                52305
SALEDATE               26770
PRICE                  60741
QUALIFIED                  0
SALE_NUM                   0
GBA                    52261
BLDG_NUM                   0
STYLE                  52261
STRUCT                 52261
GRADE                  52261
CNDTN                  52261
EXTWALL                52261
ROOF                   52261
INTWALL                52261
KITCHENS               52262
FIREPLACES                 0
USECODE                    0
LANDAREA                   0
GIS_LAST_MOD_DTTM          0
SOURCE                     0
CMPLX_NUM             106696
LIVING_GBA            106696
FULLADDRESS            52917
CITY          

In [9]:
#lok at numeric data
df.describe()


Unnamed: 0         BATHRM      HF_BATHRM      NUM_UNITS  \
count  158957.000000  158957.000000  158957.000000  106696.000000   
mean    79478.000000       1.810678       0.458237       1.198039   
std     45887.077707       0.976396       0.587571       0.596924   
min         0.000000       0.000000       0.000000       0.000000   
25%     39739.000000       1.000000       0.000000       1.000000   
50%     79478.000000       2.000000       0.000000       1.000000   
75%    119217.000000       2.000000       1.000000       1.000000   
max    158956.000000      14.000000      11.000000       6.000000   

               ROOMS          BEDRM            AYB       YR_RMDL  \
count  158957.000000  158957.000000  158686.000000  80928.000000   
mean        6.187736       2.732506    1941.987579   1998.243537   
std         2.618165       1.358864      33.640234     16.575786   
min         0.000000       0.000000    1754.000000     20.000000   
25%         4.000000       2.000000    1918.000000   1985.000000   
50%         6.000000       3.000000    1937.000000   2004.000000   
75%         7.000000       3.000000    1960.000000   2010.000000   
max        48.000000      24.000000    2019.000000   2019.000000   

                 EYB        STORIES  ...        USECODE       LANDAREA  \
count  158957.000000  106652.000000  ...  158957.000000  158957.000000   
mean     1963.718024       2.091793  ...      14.252999    2473.282158   
std        24.923150       2.933323  ...       3.725736    5059.046023   
min      1800.000000       0.000000  ...      11.000000       0.000000   
25%      1954.000000       2.000000  ...      11.000000     697.000000   
50%      1963.000000       2.000000  ...      13.000000    1649.000000   
75%      1975.000000       2.000000  ...      17.000000    3000.000000   
max      2018.000000     826.000000  ...     117.000000  942632.000000   

          CMPLX_NUM    LIVING_GBA        ZIPCODE       LATITUDE  \
count  52261.000000  52261.000000  158956.000000  158956.000000   
mean    2371.544249    888.834542   20012.694563      38.914854   
std     1114.272364    420.185822      15.627084       0.031723   
min     1001.000000      0.000000   20001.000000      38.819731   
25%     1501.000000    616.000000   20007.000000      38.895425   
50%     2265.000000    783.000000   20011.000000      38.915337   
75%     2910.000000   1060.000000   20018.000000      38.936075   
max     5621.000000   8553.000000   20392.000000      38.995540   

           LONGITUDE   CENSUS_TRACT              X              Y  
count  158956.000000  158956.000000  158720.000000  158720.000000  
mean      -77.016676    5348.216324     -77.016712      38.914846  
std         0.040938    3369.645953       0.040933       0.031682  
min       -77.113909     100.000000     -77.113135      38.820576  
25%       -77.042892    2102.000000     -77.042894      38.895432  
50%       -77.019596    5201.000000     -77.019581      38.915229  
75%       -76.988626    8302.000000     -76.988842      38.936077  
max       -76.909758   11100.000000     -76.910511      38.993646  

[8 rows x 26 columns]

In [10]:
##  look at columns and unique values
df.columns


Index(['Unnamed: 0', 'BATHRM', 'HF_BATHRM', 'HEAT', 'AC', 'NUM_UNITS', 'ROOMS',
       'BEDRM', 'AYB', 'YR_RMDL', 'EYB', 'STORIES', 'SALEDATE', 'PRICE',
       'QUALIFIED', 'SALE_NUM', 'GBA', 'BLDG_NUM', 'STYLE', 'STRUCT', 'GRADE',
       'CNDTN', 'EXTWALL', 'ROOF', 'INTWALL', 'KITCHENS', 'FIREPLACES',
       'USECODE', 'LANDAREA', 'GIS_LAST_MOD_DTTM', 'SOURCE', 'CMPLX_NUM',
       'LIVING_GBA', 'FULLADDRESS', 'CITY', 'STATE', 'ZIPCODE', 'NATIONALGRID',
       'LATITUDE', 'LONGITUDE', 'ASSESSMENT_NBHD', 'ASSESSMENT_SUBNBHD',
       'CENSUS_TRACT', 'CENSUS_BLOCK', 'WARD', 'SQUARE', 'X', 'Y', 'QUADRANT'],
      dtype='object')

In [11]:
df.BATHRM.unique()

array([ 4,  3,  2,  1,  5,  6,  7,  8, 11,  9,  0, 10, 12, 14, 13],
      dtype=int64)

In [12]:
df.HF_BATHRM.unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  9, 11], dtype=int64)

In [13]:
df.HEAT.unique()

array(['Warm Cool', 'Hot Water Rad', 'Forced Air', 'Elec Base Brd',
       'Ht Pump', 'Electric Rad', 'Wall Furnace', 'Water Base Brd',
       'Evp Cool', 'Air Exchng', 'No Data', 'Ind Unit', 'Gravity Furnac',
       'Air-Oil'], dtype=object)

In [14]:
df.BEDRM.unique()

array([ 4,  5,  3,  2,  6,  7,  1,  8,  9, 10, 11,  0, 20, 12, 16, 24, 13,
       15, 19, 14], dtype=int64)

In [15]:
df.PRICE.unique()   #  not very helpful

array([1095000.,      nan, 2100000., ...,  915500.,  908500.,  485355.])

In [16]:
df.STORIES.unique()

array([3.00e+00, 4.00e+00, 2.00e+00, 2.50e+00, 2.25e+00, 3.50e+00,
       1.00e+00,      nan, 3.25e+00, 1.50e+00, 2.75e+00, 7.00e+00,
       6.50e+01, 2.70e+00, 0.00e+00, 8.26e+02, 6.00e+00, 2.30e+00,
       5.00e+00, 2.20e+00, 3.70e+00, 1.70e+00, 3.20e+00, 1.75e+00,
       3.75e+00, 4.50e+00, 2.50e+02, 2.75e+02, 1.25e+00, 2.50e+01,
       4.75e+00, 9.00e+00, 5.00e-01, 8.25e+00, 7.50e-01, 2.33e+00,
       2.00e+01, 1.20e+01, 4.30e+01, 1.34e+00, 2.50e-01])

In [17]:
df.CITY.unique()

array(['WASHINGTON', nan], dtype=object)

In [18]:
df['WARD'].unique()

array(['Ward 2', 'Ward 1', 'Ward 6', 'Ward 5', 'Ward 3', 'Ward 4',
       'Ward 7', 'Ward 8', nan], dtype=object)

In [19]:
df.QUADRANT.unique()

array(['NW', 'SW', 'SE', 'NE', nan], dtype=object)

In [20]:
#any total missin values
dupe = df.duplicated()
df.loc[dupe]

# No 


Empty DataFrame
Columns: [Unnamed: 0, BATHRM, HF_BATHRM, HEAT, AC, NUM_UNITS, ROOMS, BEDRM, AYB, YR_RMDL, EYB, STORIES, SALEDATE, PRICE, QUALIFIED, SALE_NUM, GBA, BLDG_NUM, STYLE, STRUCT, GRADE, CNDTN, EXTWALL, ROOF, INTWALL, KITCHENS, FIREPLACES, USECODE, LANDAREA, GIS_LAST_MOD_DTTM, SOURCE, CMPLX_NUM, LIVING_GBA, FULLADDRESS, CITY, STATE, ZIPCODE, NATIONALGRID, LATITUDE, LONGITUDE, ASSESSMENT_NBHD, ASSESSMENT_SUBNBHD, CENSUS_TRACT, CENSUS_BLOCK, WARD, SQUARE, X, Y, QUADRANT]
Index: []

[0 rows x 49 columns]

In [21]:
#df.PRICE
len(df)

158957

In [22]:
# look at rows that have null PRICE

#df.loc[df['PRICE'] > 0]     #98216

#df.loc[df['PRICE'].isnull()    #60741
 

nullprice=df['PRICE'].isnull()
df.loc[nullprice]
       


Unnamed: 0  BATHRM  HF_BATHRM           HEAT AC  NUM_UNITS  ROOMS  \
1                1       3          1      Warm Cool  Y        2.0     11   
4                4       2          1      Warm Cool  Y        1.0     11   
6                6       1          0      Warm Cool  Y        2.0      5   
9                9       1          1  Hot Water Rad  Y        1.0      6   
10              10       3          0     Forced Air  N        3.0     12   
11              11       5          0  Hot Water Rad  Y        3.0     16   
12              12       2          0  Hot Water Rad  N        2.0      9   
13              13       2          0      Warm Cool  Y        2.0     11   
15              15       2          1      Warm Cool  Y        2.0      9   
17              17       2          0  Hot Water Rad  N        1.0      6   
18              18       3          1  Hot Water Rad  Y        2.0     10   
21              21       3          0     Forced Air  Y        2.0     12   
26              26       1          0  Hot Water Rad  N        1.0     10   
28              28       3          0      Warm Cool  Y        2.0     10   
30              30       2          1     Forced Air  Y        2.0      8   
31              31       3          0     Forced Air  Y        2.0      9   
33              33       2          1     Forced Air  Y        2.0     10   
34              34       3          1     Forced Air  Y        2.0     10   
35              35       3          1     Forced Air  Y        2.0      8   
36              36       3          1      Warm Cool  Y        2.0     10   
38              38       3          1     Forced Air  Y        2.0      9   
39              39       3          1      Warm Cool  Y        2.0      9   
47              47       2          1     Forced Air  N        2.0      9   
49              49       3          1      Warm Cool  Y        2.0      8   
51              51       3          0     Forced Air  Y        3.0      9   
53              53       2          1      Warm Cool  Y        2.0      7   
56              56       5          1  Hot Water Rad  Y        3.0     15   
57              57       1          0  Hot Water Rad  Y        1.0      6   
60              60       2          0  Hot Water Rad  N        2.0      9   
63              63       3          1     Forced Air  Y        2.0     13   
...            ...     ...        ...            ... ..        ...    ...   
158845      158845       1          0      Warm Cool  Y        NaN      3   
158847      158847       2          0      Warm Cool  Y        NaN      6   
158848      158848       1          0      Warm Cool  Y        NaN      3   
158849      158849       1          0      Warm Cool  Y        NaN      3   
158850      158850       1          0      Warm Cool  Y        NaN      3   
158852      158852       1          0      Warm Cool  Y        NaN      3   
158855      158855       1          0      Warm Cool  Y        NaN      3   
158856      158856       1          0      Warm Cool  Y        NaN      2   
158857      158857       1          0      Warm Cool  Y        NaN      4   
158859      158859       2          0      Warm Cool  Y        NaN      6   
158860      158860       1          0      Warm Cool  Y        NaN      4   
158863      158863       1          0      Warm Cool  Y        NaN      3   
158865      158865       1          0      Warm Cool  Y        NaN      4   
158866      158866       1          0      Warm Cool  Y        NaN      4   
158870      158870       2          0      Warm Cool  Y        NaN      7   
158872      158872       1          0      Warm Cool  Y        NaN      4   
158879      158879       1          0      Warm Cool  Y        NaN      4   
158883      158883       1          0      Warm Cool  Y        NaN      4   
158889      158889       1          0     Forced Air  Y        NaN      4   
158913      158913       2          1     Forced Air  Y        NaN      4   
1589

In [23]:
#look at the data
df.describe()

Unnamed: 0         BATHRM      HF_BATHRM      NUM_UNITS  \
count  158957.000000  158957.000000  158957.000000  106696.000000   
mean    79478.000000       1.810678       0.458237       1.198039   
std     45887.077707       0.976396       0.587571       0.596924   
min         0.000000       0.000000       0.000000       0.000000   
25%     39739.000000       1.000000       0.000000       1.000000   
50%     79478.000000       2.000000       0.000000       1.000000   
75%    119217.000000       2.000000       1.000000       1.000000   
max    158956.000000      14.000000      11.000000       6.000000   

               ROOMS          BEDRM            AYB       YR_RMDL  \
count  158957.000000  158957.000000  158686.000000  80928.000000   
mean        6.187736       2.732506    1941.987579   1998.243537   
std         2.618165       1.358864      33.640234     16.575786   
min         0.000000       0.000000    1754.000000     20.000000   
25%         4.000000       2.000000    1918.000000   1985.000000   
50%         6.000000       3.000000    1937.000000   2004.000000   
75%         7.000000       3.000000    1960.000000   2010.000000   
max        48.000000      24.000000    2019.000000   2019.000000   

                 EYB        STORIES  ...        USECODE       LANDAREA  \
count  158957.000000  106652.000000  ...  158957.000000  158957.000000   
mean     1963.718024       2.091793  ...      14.252999    2473.282158   
std        24.923150       2.933323  ...       3.725736    5059.046023   
min      1800.000000       0.000000  ...      11.000000       0.000000   
25%      1954.000000       2.000000  ...      11.000000     697.000000   
50%      1963.000000       2.000000  ...      13.000000    1649.000000   
75%      1975.000000       2.000000  ...      17.000000    3000.000000   
max      2018.000000     826.000000  ...     117.000000  942632.000000   

          CMPLX_NUM    LIVING_GBA        ZIPCODE       LATITUDE  \
count  52261.000000  52261.000000  158956.000000  158956.000000   
mean    2371.544249    888.834542   20012.694563      38.914854   
std     1114.272364    420.185822      15.627084       0.031723   
min     1001.000000      0.000000   20001.000000      38.819731   
25%     1501.000000    616.000000   20007.000000      38.895425   
50%     2265.000000    783.000000   20011.000000      38.915337   
75%     2910.000000   1060.000000   20018.000000      38.936075   
max     5621.000000   8553.000000   20392.000000      38.995540   

           LONGITUDE   CENSUS_TRACT              X              Y  
count  158956.000000  158956.000000  158720.000000  158720.000000  
mean      -77.016676    5348.216324     -77.016712      38.914846  
std         0.040938    3369.645953       0.040933       0.031682  
min       -77.113909     100.000000     -77.113135      38.820576  
25%       -77.042892    2102.000000     -77.042894      38.895432  
50%       -77.019596    5201.000000     -77.019581      38.915229  
75%       -76.988626    8302.000000     -76.988842      38.936077  
max       -76.909758   11100.000000     -76.910511      38.993646  

[8 rows x 26 columns]

In [24]:
#what is orginal rows & columns?
df.shape


(158957, 49)

In [29]:
# Delete column from dataframe that are not needed now, not interested in location gis data
#  Also, looked at data in exce by importing csv file.... pain writing python code !!  :-)
# 'NATIONALGRID','LATITUDE', 'LONGITUDE',  'X', 'Y',''

#df.drop?
#df.shape   #(158957, 49)

#df.drop(['NATIONALGRID','LATITUDE', 'LONGITUDE',  'X', 'Y'], axis=1, inplace=True)

#df.shape  #(158957, 44)  num of rows now 44!

df.columns   #  dropped columns not in column list



Index(['Unnamed: 0', 'BATHRM', 'HF_BATHRM', 'HEAT', 'AC', 'NUM_UNITS', 'ROOMS',
       'BEDRM', 'AYB', 'YR_RMDL', 'EYB', 'STORIES', 'SALEDATE', 'PRICE',
       'QUALIFIED', 'SALE_NUM', 'GBA', 'BLDG_NUM', 'STYLE', 'STRUCT', 'GRADE',
       'CNDTN', 'EXTWALL', 'ROOF', 'INTWALL', 'KITCHENS', 'FIREPLACES',
       'USECODE', 'LANDAREA', 'GIS_LAST_MOD_DTTM', 'SOURCE', 'CMPLX_NUM',
       'LIVING_GBA', 'FULLADDRESS', 'CITY', 'STATE', 'ZIPCODE',
       'ASSESSMENT_NBHD', 'ASSESSMENT_SUBNBHD', 'CENSUS_TRACT', 'CENSUS_BLOCK',
       'WARD', 'SQUARE', 'QUADRANT'],
      dtype='object')

In [30]:
# mean price by num of bedrooms

df['PRICE'].groupby(df['BEDRM']).mean()

BEDRM
0     1.992876e+06
1     1.927088e+06
2     6.482021e+05
3     4.821091e+05
4     6.659285e+05
5     1.042489e+06
6     1.266913e+06
7     1.721509e+06
8     8.107116e+05
9     2.718745e+06
10    6.924450e+05
11    1.025980e+06
12    1.547980e+06
13    4.425000e+05
14    9.250000e+05
15    1.105000e+06
16             NaN
19             NaN
20    1.900000e+06
24             NaN
Name: PRICE, dtype: float64

In [31]:
#mean price by city quadrant
df['PRICE'].groupby(df['QUADRANT']).mean()

QUADRANT
NE    3.928715e+05
NW    1.317785e+06
SE    3.682260e+05
SW    3.470489e+05
Name: PRICE, dtype: float64

In [32]:
#create pivot table --mean value
pd.pivot_table(df, values=['PRICE'],index=['BEDRM','BATHRM'])

PRICE
BEDRM BATHRM              
0     0       2.602079e+06
      1       1.989367e+06
      2       5.677480e+05
      3       2.040500e+05
      4       6.715590e+06
1     0       2.860000e+05
      1       1.887415e+06
      2       2.753084e+06
      3       6.520667e+05
      4       2.539750e+05
2     0       6.894500e+05
      1       4.706987e+05
      2       7.829985e+05
      3       7.162117e+05
      4       8.532768e+05
3     0       4.225000e+05
      1       3.094116e+05
      2       5.031922e+05
      3       7.185585e+05
      4       1.013861e+06
      5       2.219800e+06
      6       4.000000e+05
      7       4.217000e+06
4     0       8.500000e+05
      1       3.397873e+05
      2       5.151250e+05
      3       7.792648e+05
      4       7.937731e+05
      5       1.825532e+06
      6       2.264856e+06
...                    ...
9     3       5.789950e+05
      4       5.416591e+05
      5       1.513591e+06
      6       6.293000e+06
      7       3.286414e+06
      8       5.405500e+06
      9       8.811935e+06
      10      4.450000e+06
      12      1.225000e+07
10    3       2.503333e+05
      4       4.324734e+05
      5       9.980000e+05
      6       1.147917e+06
      7       7.950000e+05
      11      1.375000e+06
11    3       2.415600e+05
      5       1.400000e+05
      8       4.200000e+05
      9       4.562800e+05
      10      1.700000e+06
      11      1.850000e+06
12    2       2.100000e+05
      4       4.353146e+05
      5       2.330000e+05
      6       2.665080e+05
      7       2.396029e+07
13    6       4.425000e+05
14    4       9.250000e+05
15    10      1.105000e+06
20    10      1.900000e+06

[99 rows x 1 columns]

In [33]:
#look at year built , price

#create pivot table --mean value
pd.pivot_table(df, values=['PRICE'],index=['AYB'])

PRICE
AYB                 
1754.0  7.100000e+06
1765.0  1.100000e+06
1776.0  4.742500e+05
1780.0  7.716667e+05
1790.0  1.512167e+06
1794.0  3.400000e+06
1796.0  3.640000e+06
1800.0  8.021075e+05
1801.0  9.063000e+06
1802.0  1.812500e+06
1803.0  9.100000e+05
1805.0  8.533057e+06
1807.0  3.075000e+06
1810.0  2.308750e+06
1811.0  3.175000e+06
1812.0  4.945000e+05
1813.0  2.063750e+06
1815.0  2.147814e+06
1816.0  3.611250e+06
1818.0  1.015127e+06
1819.0  1.112500e+06
1820.0  2.264750e+06
1822.0  8.290000e+05
1825.0  1.640000e+06
1830.0  9.848625e+05
1833.0  6.350000e+05
1834.0  9.170000e+05
1835.0  6.500000e+05
1840.0  1.195769e+06
1842.0  3.050000e+05
...              ...
1989.0  2.064534e+07
1990.0  6.397416e+05
1991.0  4.627884e+05
1992.0  8.326606e+05
1993.0  7.609145e+05
1994.0  6.190759e+05
1995.0  7.476852e+05
1996.0  8.773640e+05
1997.0  4.788404e+05
1998.0  6.088357e+05
1999.0  5.590457e+05
2000.0  6.961120e+05
2001.0  5.647672e+05
2002.0  4.836677e+05
2003.0  6.713385e+05
2004.0  5.007837e+05
2005.0  5.526254e+05
2006.0  5.478528e+05
2007.0  5.223140e+05
2008.0  5.478527e+05
2009.0  5.609646e+05
2010.0  5.143974e+05
2011.0  6.377323e+05
2012.0  6.529205e+05
2013.0  7.369201e+05
2014.0  6.891572e+05
2015.0  6.370203e+05
2016.0  5.889125e+05
2017.0  9.486434e+05
2018.0  6.858841e+05

[200 rows x 1 columns]

In [34]:
#look at year built , number of bedrooms

#create pivot table --mean value
pd.pivot_table(df, values=['BEDRM'],index=['AYB'])

BEDRM
AYB             
1754.0  6.500000
1765.0  2.000000
1776.0  3.333333
1780.0  2.000000
1782.0  3.000000
1784.0  4.000000
1785.0  2.000000
1787.0  8.000000
1788.0  4.000000
1790.0  3.666667
1791.0  4.000000
1793.0  4.000000
1794.0  4.000000
1795.0  6.000000
1796.0  4.500000
1797.0  9.000000
1799.0  5.000000
1800.0  2.318182
1801.0  5.250000
1802.0  3.500000
1803.0  2.500000
1805.0  6.111111
1806.0  2.000000
1807.0  5.000000
1808.0  3.000000
1810.0  4.000000
1811.0  3.500000
1812.0  2.666667
1813.0  2.500000
1815.0  3.222222
...          ...
1990.0  2.545775
1991.0  1.737179
1992.0  3.741935
1993.0  3.902439
1994.0  3.319820
1995.0  3.134615
1996.0  3.384058
1997.0  3.006024
1998.0  2.137584
1999.0  2.965079
2000.0  2.488304
2001.0  3.101083
2002.0  2.171737
2003.0  2.047546
2004.0  1.675460
2005.0  1.623486
2006.0  1.729074
2007.0  1.927543
2008.0  2.151386
2009.0  2.297940
2010.0  2.905263
2011.0  3.264781
2012.0  3.152968
2013.0  2.431990
2014.0  2.762811
2015.0  2.205298
2016.0  2.289370
2017.0  2.601351
2018.0  3.510204
2019.0  6.000000

[220 rows x 1 columns]